react-component/tooltip

README.md, src/Tooltip.jsx
It's really needed when using something like https://github.com/balloob/react-sidebar
=> add possibilty to mount tooltips to custom html node

src/Tooltip.jsx
fix ant-design/ant-design#811, related https://github.com/react-component/trigger/pull/4
=> fix props passed to children

src/Tooltip.jsx, tests/index.js
This is a follow-up of https://github.com/react-component/trigger/pull/17
=> Allow function prop for overlay

src/Tooltip.jsx
rc-trigger 更新，没有popupDomNode属性
=> fix getPopupDomNode

examples/simple.js, index.js, tests/index.js
When looking at the test code I felt it needed some love.
This is what I changed:
* Extracted logic into re-usable functions
* Made everything use ES6 syntax
* Tightened up dependency imports
* Re-named tests to be more descriptive
=> Clean up test code

README.md
=> Add child note

README.md
The function acts as both a setter and getter.
This is spurred from https://github.com/react-component/tooltip/issues/41
=> Elaborated more on getTooltipContainer

HISTORY.md, package.json
To fix [issue #74](https://github.com/react-component/tooltip/issues/74)
=> [Add] Add babel-runtime dependency

.gitignore, index.js, package.json, src/index.js
ref: https://github.com/react-component/react-component.github.io/issues/12
=> feat: expose es files

src/Tooltip.jsx
=> Update Tooltip.jsx +afterVisibleChange

examples/arrowContent.js, examples/onVisibleChange.js, examples/placement.js, package-lock.json
Had to add few divs and styling to make they look uniform in English (word has difference length)
=> translated to English

README.md
Swapped Firefox/Chrome and Safari/Opera to fit with the header
=> Fix Browsers support order in README.md

src/Content.tsx, src/Tooltip.tsx
Ref: https://github.com/ant-design/ant-design/pull/19408
=> fix: ts type

src/placements.tsx
Ref: https://github.com/ant-design/ant-design/pull/19408
=> improve placements type

assets/bootstrap.less, assets/bootstrap_white.less
https://github.com/react-component/tooltip/issues/217
=> fix less import path

README.md, docs/demo/showArrow.md, docs/examples/arrowVisible.tsx, docs/examples/showArrow.tsx, src/Tooltip.tsx, tests/index.test.js
Its useful which can hide arrow. If you dont like in some case
=> Add arrowVisible option into tooltip which can hide arrow

README.md
=> chore(README)

.dumirc.ts, README.md, package.json, src/Tooltip.tsx
close https://github.com/react-component/tooltip/issues/447
=> docs: site doc

package.json, src/Tooltip.tsx
ref https://github.com/ant-design/ant-design/issues/44830
=> feat: pass fresh

package.json
fix https://github.com/react-component/tooltip/issues/457
=> fix: fix npm files

.dumi/app.tsx, .dumi/tsconfig.json, .github/workflows/react-component-ci.yml, README.md, package.json, src/Tooltip.tsx
ref: https://github.com/react-component/tooltip/issues/429
=> chore: So many chores
