react-component/tooltip

README.md, assets/bootstrap.less, examples/simple.js, src/Popup.jsx, tests/index.spec.js
Implements 4 new positions for the popup:
topLeft:
topRight:
bottomLeft:
bottomRight:
=> Implements topLeft topRight bottomLeft and bottomRight Popup placements

README.md, examples/formError.js, examples/handleVisibleChange.js, examples/points.js, examples/simple.js, package.json, src/Popup.jsx, src/Tooltip.jsx, tests/index.spec.js
Context doesn't properly get carried over when using React 0.14
To solve this you need to upgrade the dependencies to React 0.14 and in Tooltip.jsx call ReactDOM.unstable_renderSubtreeIntoContainer instead of React.render.
=> Upgrade to React 0.14: Fixes a context issue as well

README.md, examples/simple.js, src/Popup.jsx, src/Tooltip.jsx, tests/index.spec.js
It looks like you *can* do this already by passing an object as the placement prop. However, that wasn't working well for me. It's much more explicit to pass an offsetX and offsetY - and, this approach will also allow you to use an offset with the pre-supplied positions.
=> Adds ability to specify offsetX and offsetY for a tooltip

examples/formError.js, examples/handleVisibleChange.js, examples/placement.js, examples/simple.js, package.json, tests/index.spec.js
1. add object-assign for examples/simple.js
2. eslint for examples/ & tests/
=> devDependencies + object-assign && eslint

package.json
Since there's only one license the property should be of the singular
form.
=> Change form of package.json property to singular

package.json, src/Tooltip.jsx
- as React.PropTypes is being deprecated
- Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
- Solution: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
=> Migrated deprecated React.PropTypes and React.createClass

README.md, src/Tooltip.jsx
Added ariaId prop, which gets attached to the tooltips inner content container and can be used with aria-describedby for better accessibility and Screenreader-Support.
=> Added Screenreader-Support with ariaId

README.md, src/Tooltip.jsx
Defined in: https://github.com/react-component/animate#props
I've also added a PR for rc-trigger: https://github.com/react-component/trigger/pull/70 that updates the outdated readme accordingly
=> Update transitionName proptypes so it can be a string or object

README.md
Currently https://react-component.github.io/tooltip/ shows mixed content.
In addition, Gemnasium has been closed. Shall we remove this badge?
=> Fix mixed content and simplify links

package.json
"*" version is wrong peer dependency for react library and a bad tone (for example some tools like microsoft rush gives Error about using peer dependencies like this)
=> fix: change react deps to right spread

README.md, src/Tooltip.tsx
`trigger: ActionType` => `trigger: ActionType | ActionType[]`
=> fix: fix trigger type def

README.md, examples/simple.js, package.json, src/Tooltip.tsx, tests/index.test.js
@afc163  fix [#19536](https://github.com/ant-design/ant-design/issues/19536), support `autoDestroy` prop.
=> chore: upgrade trigger to 4.2.1

README.md, examples/simple.js, src/Content.tsx, src/Tooltip.tsx, tests/index.test.js
ref: https://github.com/ant-design/ant-design/pull/23155
要做自定义得支持下 style
=> feat: support to config overlay inner style

README.md
This was brought up more than one time as an issue before, and I think updating the README to be slightly more clear may help prevent future questions about this.
=> Update README.md to have clearer explanation about need for Tooltip to have correct child node

package.json
An old version does not work well with react 18 / the page freezing while triggering tooltip visibility
=> fix: upgrade rc-trigger from 5.0.0 to 5.3.1

package.json, src/Tooltip.tsx, tests/index.test.tsx
- https://github.com/ant-design/ant-design/discussions/40099
=> feat: tooltip support show-arrow cls when showArrow not falsy

README.md, package.json, src/Tooltip.tsx, tests/index.test.tsx
=> feat: arrow support className

src/index.tsx
This type makes typescript happy about the `forceAlign` method on a tooltip ref, so I thought it would be good to go on and export it.
This makes [this example](https://github.com/react-component/slider/blob/9d9fb1ab4c0d58a725985d19f1e1011910bb6c96/docs/examples/components/TooltipSlider.tsx#L25) compile in typescript.
=> patch: export tooltip ref

src/Tooltip.tsx
ref: https://github.com/react-component/tooltip/issues/292
=> chore:  pick types from upstream

package.json, src/Tooltip.tsx, tests/index.test.tsx
ref https://github.com/ant-design/ant-design/issues/45541
=> feat: Tooltip ref support nativeElement

src/Tooltip.tsx
This PR adds the forceRender type as a supplement.
=> add forceRender Type
